### ISSUE TITLE
New update gives error 

### ISSUE THREAD

**Issue by denisac** [sameday-courier/woocommerce-plugin#114]
Hi
Upon hitting the generate AWB button, there is a fatal error shown in the screen with the following error logged:

Fatal error: Uncaught JsonException: Syntax error in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php:340 Stack trace: #0 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(340): json_decode('', true, 512, 4194304) #1 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(501): Sameday->postAwb(Array) #2 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(307): {closure}('') #3 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #4 /home3/r72333gent/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #5 /home3/r72333gent/public_html/wp-admin/admin-post.php(85): do_action('admin_post_add_...') #6 {main} thrown in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php on line 340

Ideas how we could solve this ?

Thanks

**Comment by Soptareanu** [comment]
> Hi Upon hitting the generate AWB button, there is a fatal error shown in the screen with the following error logged:
> 
> Fatal error: Uncaught JsonException: Syntax error in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php:340 Stack trace: #0 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(340): json_decode('', true, 512, 4194304) #1 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(501): Sameday->postAwb(Array) #2 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(307): {closure}('') #3 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #4 /home3/r72333gent/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #5 /home3/r72333gent/public_html/wp-admin/admin-post.php(85): do_action('admin_post_add_...') #6 {main} thrown in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php on line 340
> 
> Ideas how we could solve this ?
> 
> Thanks

Buna Denisa,

       Verific imediat.

**Comment by Soptareanu** [comment]
> Hi Upon hitting the generate AWB button, there is a fatal error shown in the screen with the following error logged:
> 
> Fatal error: Uncaught JsonException: Syntax error in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php:340 Stack trace: #0 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(340): json_decode('', true, 512, 4194304) #1 /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(501): Sameday->postAwb(Array) #2 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(307): {closure}('') #3 /home3/r72333gent/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #4 /home3/r72333gent/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #5 /home3/r72333gent/public_html/wp-admin/admin-post.php(85): do_action('admin_post_add_...') #6 {main} thrown in /home3/r72333gent/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php on line 340
> 
> Ideas how we could solve this ?
> 
> Thanks

Am revenit cu un fix. Puteti sa faceti un update si sa incercati din nou.

**Comment by denisac** [comment]
You rock !!  
Se genereaza corect AWB-ul 

Multumesc
