### ISSUE TITLE
PHP error / probleme checkout

### ISSUE THREAD

**Issue by lazarlehel** [sameday-courier/woocommerce-plugin#150]
In continu primim aceasta eroare, din cauza caruia ceheckoutul nu poate fi finalizat.  

`[07-Aug-2023 13:45:05 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SamedayCourierHelperClass::parseShippingMethodCode() must be of the type string, null given, called in /home/.../public/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php on line 567 and defined in /home/.../public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php:217
Stack trace:
#0 /home/.../public/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(567): SamedayCourierHelperClass::parseShippingMethodCode()
#1 /home/.../public/wp-includes/class-wp-hook.php(308): wps_sameday_shipping_options_layout()
#2 /home/.../public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#3 /home/.../public/wp-includes/plugin.php(517): WP_Hook->do_action()
#4 /home/.../public/wp-content/plugins/woocommerce/templates/checkout/review-order.php(73): do_action()
#5 /home/.../ww in /home/.../public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php on line 217`

**Comment by lazarlehel** [comment]
Se pare ca problema e de la un alt plugin pentru livrari ...
