### ISSUE TITLE
Operation timed out after 10000 milliseconds with 0 out of 0 bytes received 

### ISSUE THREAD

**Issue by colibry** [sameday-courier/woocommerce-plugin#34]
Hello, from yesterday, around 16.00 i got this error on my website at add to cart action.

If i deactivate the lockers service on the module the problem disappear. 
Can help me with a fix for this problem?

Thanks.

**Comment by colibry** [comment]
On admin backend when i click to Refresh Lockers i get this :

A apărut o eroare de tipul E_ERROR pe linia 54 a fișierului /var/www/vhosts/smartprotection.ro/httpdocs/wp-content/plugins/samedaycourier-shipping/lib/sameday-courier/src/Sameday/HttpClients/SamedayCurlHttpClient.php. Mesaj eroare: Uncaught Sameday\Exceptions\SamedaySDKException: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received in /var/www/vhosts/smartprotection.ro/httpdocs/wp-content/plugins/samedaycourier-shipping/lib/sameday-courier/src/Sameday/HttpClients/SamedayCurlHttpClient.php:54
Stack trace:
#0 /var/www/vhosts/smartprotection.ro/httpdocs/wp-content/plugins/samedaycourier-shipping/lib/sameday-courier/src/Sameday/SamedayClient.php(133): Sameday\HttpClients\SamedayCurlHttpClient->send('https://api.sam...', 'GET', '', Array, 10)
#1 /var/www/vhosts/smartprotection.ro/httpdocs/wp-content/plugins/samedaycourier-shipping/lib/sameday-courier/src/Sameday/Sameday.php(306): Sameday\SamedayClient->sendRequest(Object(Sameday\Http\SamedayRequest))
#2 /var/www/vhosts/smartprotection.ro/httpdocs/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(175): Sameday\Sameday->getLockers(Object(Sameday\Requests\SamedayGetLockersRequest))
#3 /var/www/vhosts/smartprotection.ro/httpdocs/wp-conten
