### ISSUE TITLE
Generate AWB în modul test cauzează eroare critică

### ISSUE THREAD

**Issue by akaleeroy** [sameday-courier/woocommerce-plugin#53]
Am instalat extensia și am configurat-o cu **credențialele de test** și e bifat și **Is testing**

Am plasat o comandă de test (cu locker easybox) și când am dat pe Generate awb am primit eroare critică din WordPress.

Pe mail am primit următoarele detalii. Din păcate stack trace-ul așa era, trunchiat

Versiunea WordPress 5.8.1
Modulul curent: SamedayCourier Shipping (versiunea 1.0.28)
Versiunea PHP 7.4.23

### Detalii eroare

```
A apărut o eroare de tipul E_ERROR pe linia 172 a fișierului /home/eurotr/public_html/kifkif/wp-content/plugins/woocommerce-plugin-master/lib/sameday-courier/src/Sameday/SamedayClient.php. Mesaj eroare: Uncaught Sameday\Exceptions\SamedayOtherException in /home/eurotr/public_html/kifkif/wp-content/plugins/woocommerce-plugin-master/lib/sameday-courier/src/Sameday/SamedayClient.php:172
Stack trace:
#0 /home/eurotr/public_html/kifkif/wp-content/plugins/woocommerce-plugin-master/lib/sameday-courier/src/Sameday/Sameday.php(164): Sameday\SamedayClient->sendRequest(Object(Sameday\Http\SamedayRequest))
#1 /home/eurotr/public_html/kifkif/wp-content/plugins/woocommerce-plugin-master/classes/samedaycourier-sameday-class.php(423): Sameday\Sameday->postAwb(Object(Sameday\Requests\SamedayPostAwbRequest))
#2 /home/eurotr/public_html/kifkif/wp-content/plugins/woocommerce-plugin-master/samedaycourier-shipping.php(474): Sameday->postAwb(Array)
#3 /home/eurotr/public_html/kifkif/wp-includes/class-wp-hook.php(303): {closure}('')
#4 /home/eurotr/public_html/kifkif/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#5 /home/eurotr/public_html/kifkif/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /hom
```

**Comment by akaleeroy** [comment]
Solved from account configuration side?

**Comment by cristian-calin** [comment]
Primesc exact aceeasi eroare folosind credentialele de test. Cum ai rezolvat problema? Ai trecut pe credentialele de productie? Acolo mai sunt erori? Merci!
