### ISSUE TITLE
PHP Fatal Error samedayCourierHelperClass::getApiURL()

### ISSUE THREAD

**Issue by rwkyyy** [sameday-courier/woocommerce-plugin#67]
Hello, having the following issue with the latest update on multiple website:
```
PHP message: PHP Fatal error: Uncaught TypeError: Return value of SamedayCourierHelperClass::getApiUrl() must be of the type string, null returned in /www/accnt-879/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php:52
Stack trace:
#0 /www/accnt-879/public/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(505): SamedayCourierHelperClass::getApiUrl()
#1 /www/accnt-879/public/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(812): Sameday->showAwbHistory(21765)
#2 /www/accnt-879/public/wp-includes/class-wp-hook.php(307): {closure}(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#3 /www/accnt-879/public/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 /www/accnt-879/public/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#5 /www/accnt-879/public/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php(522): do_action('woocommerce_ad" while reading response header from upstream, client: spoof(ip), server: domain.tld, request: "GET /wp-admin/post.php?post=21765&action=edit HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.4-fpm-roxiro.sock:", host: "domain.tld:35762", referrer: "https://domain.tld/wp-admin/edit.php?s=21765&post_status=all&post_type=shop_order&action=-1&m=0&_customer_user&paged=1&action2=-1"
```

The website are up-to-date (core, theme, plugins).

Thank you!

**Comment by georgefusefabric** [comment]
@rwkyyy please try to update settings for sameday plugin from /wp-admin/admin.php?page=wc-settings&tab=shipping&section=samedaycourier

**Comment by neagugeorge** [comment]
@rwkyyy please try to update settings for sameday plugin from /wp-admin/admin.php?page=wc-settings&tab=shipping&section=samedaycourier .

**Comment by rwkyyy** [comment]
@neagugeorge what settings should I update? opened the page and resaved, the issue still persists.
