### ISSUE TITLE
Fatal error dupa ultimile update 

### ISSUE THREAD

**Issue by roniduicu** [sameday-courier/woocommerce-plugin#72]
Buna ziua,
Dupa ultimile 2 update-uri plug-in ul blocheaza siteul.
Nu pot fi adaugate produse in cos sau direct fatal error.
Am desactivat momentan plug-in insa avem nevoie de el.
Ne puteti ajuta

**Comment by Soptareanu** [comment]
Ce eroare primiti ?

**Comment by roniduicu** [comment]
![A4A084C6-10B3-4D5C-B93B-329F4071A81A](https://user-images.githubusercontent.com/62900879/156514420-790856f5-985a-4525-9ceb-1bee3df671b7.png)

**Comment by roniduicu** [comment]
La activarea plugin-ului asta se intampla cand adaug un produs in cos. 
vezi imagine sus.

**Comment by roniduicu** [comment]
Mesaj eroare: Uncaught TypeError: Return value of SamedayCourierHelperClass::getHostCountry() must be of the type string, null returned in /home3/r84983semp/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php:52
Stack trace:
#0 /home3/r84983semp/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-helper-class.php(60): SamedayCourierHelperClass::getHostCountry()
#1 /home3/r84983semp/public_html/wp-content/plugins/samedaycourier-shipping/classes/samedaycourier-sameday-class.php(157): SamedayCourierHelperClass::getApiUrl()
#2 /home3/r84983semp/public_html/wp-content/plugins/samedaycourier-shipping/samedaycourier-shipping.php(474): Sameday->refreshLockers()
#3 /home3/r84983semp/public_html/wp-includes/class-wp-hook.php(307): {closure}('')
#4 /home3/r84983semp/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#5 /home3/r84983semp/public_html/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#6 /home3/r84983semp/public_html/

**Comment by Soptareanu** [comment]
> Buna ziua, Dupa ultimile 2 update-uri plug-in ul blocheaza siteul. Nu pot fi adaugate produse in cos sau direct fatal error. Am desactivat momentan plug-in insa avem nevoie de el. Ne puteti ajuta

Incercati sa dezactivați pluginul, apoi sa il reactivati si sa refaceti toti pasii de setup, autentificarea si importul de servicii si pickuppointuri.

**Comment by roniduicu** [comment]
Am facut cele enumerate mai sus.
Acum se pot adauga produse in cos si checkout.
Insa daca incerc sa updatez lista de servici, lista de lockers imi da eroarea de mai sus

**Comment by roniduicu** [comment]
> > Buna ziua, Dupa ultimile 2 update-uri plug-in ul blocheaza siteul. Nu pot fi adaugate produse in cos sau direct fatal error. Am desactivat momentan plug-in insa avem nevoie de el. Ne puteti ajuta
> 
> Incercati sa dezactivați pluginul, apoi sa il reactivati si sa refaceti toti pasii de setup, autentificarea si importul de servicii si pickuppointuri.

Am facut cele enumerate mai sus.
Acum se pot adauga produse in cos si checkout.
Insa daca incerc sa updatez lista de servici, lista de lockers imi da eroarea de mai sus

**Comment by Soptareanu** [comment]
> Am facut cele enumerate mai sus. Acum se pot adauga produse in cos si checkout. Insa daca incerc sa updatez lista de servici, lista de lockers imi da eroarea de mai sus

Ce versiune a pluginului folosiți?

**Comment by roniduicu** [comment]
> > Am facut cele enumerate mai sus. Acum se pot adauga produse in cos si checkout. Insa daca incerc sa updatez lista de servici, lista de lockers imi da eroarea de mai sus
> 
> Ce versiune a pluginului folosiți?

Ultima: 1.2.6

**Comment by Soptareanu** [comment]
> > > Am facut cele enumerate mai sus. Acum se pot adauga produse in cos si checkout. Insa daca incerc sa updatez lista de servici, lista de lockers imi da eroarea de mai sus
> > 
> > 
> > Ce versiune a pluginului folosiți?
> 
> Ultima: 1.2.6

Situația semnalata de dvs. a fost întâlnită la versiuni mai vechi. Fusese demult remediată.

**Comment by roniduicu** [comment]
> > > > Am facut cele enumerate mai sus. Acum se pot adauga produse in cos si checkout. Insa daca incerc sa updatez lista de servici, lista de lockers imi da eroarea de mai sus
> > > 
> > > 
> > > Ce versiune a pluginului folosiți?
> > 
> > 
> > Ultima: 1.2.6
> 
> Situația semnalata de dvs. a fost întâlnită la versiuni mai vechi. Fusese demult remediată.

Va cred. Insa asta este cu ce ma confrunt.
Sunt pe mobil insa versiunea este 1.2.6
![533B4752-99E9-4AB8-887E-E6F41D4AE119](https://user-images.githubusercontent.com/62900879/156945130-9bf6d1ca-ea74-409e-9cdc-5ca1dce8c939.png)

daca aveti o alta sugestie sunt deschis. Nu sunt cel mai priceput dar lucruri de baza pot sa fac.

**Comment by Soptareanu** [comment]
> Buna ziua, Dupa ultimile 2 update-uri plug-in ul blocheaza siteul. Nu pot fi adaugate produse in cos sau direct fatal error. Am desactivat momentan plug-in insa avem nevoie de el. Ne puteti ajuta

Buna ziua,

         Am facut un mix fix. Va rog sa faceti update la versiunea 1.2.7. si sa ne comunicati daca a fost remediata situatia.
         De asemenea v-as recomanda sa pastram comunicarea pe adresa de email platforme@sameday.ro
